name: Test
on:
  push:
    branches:
      - main
      - develop
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - develop
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"
permissions:
  contents: read
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.18,1.22]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: go build -v ./...
      - name: Test
        run: make test-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
